const {chromium}=require('C:/Users/Admin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {pathToFileURL}=require('url');
const path=require('path');
const fs=require('fs');
const assert=require('assert/strict');
(async()=>{
  const browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1000,height:294},colorScheme:'dark'});
  for(const theme of ['dark','light']){
    await page.goto(pathToFileURL(path.resolve(`output/contribution-racer${theme==='dark'?'-dark':''}.svg`)).href);
    await page.evaluate(()=>document.getAnimations().forEach(a=>{a.pause();a.currentTime=0}));
    const start=await page.locator('.car').boundingBox();
    await page.screenshot({path:`tmp/profile-preview/racer-${theme}.png`});
    await page.evaluate(()=>document.getAnimations().forEach(a=>a.currentTime=6000));
    const moved=await page.locator('.car').boundingBox();
    assert.ok(Math.hypot(moved.x-start.x,moved.y-start.y)>20);
    const count=await page.locator('.day').count(); assert.equal(count,367);
    await page.screenshot({path:`tmp/profile-preview/racer-${theme}-moving.png`});
    await page.emulateMedia({reducedMotion:'reduce'});
    assert.equal(await page.evaluate(()=>document.getAnimations().length),0);
    await page.emulateMedia({reducedMotion:'no-preference'});
    console.log(theme,{cells:count,start,moved,reducedMotion:'passed'});
    await page.setViewportSize({width:1000,height:250});
    await page.goto(pathToFileURL(path.resolve(`output/github-stats${theme==='dark'?'-dark':''}.svg`)).href);
    const outside=await page.locator('text').evaluateAll(els=>els.filter(el=>{const b=el.getBBox();return b.x<0||b.x+b.width>1000}).map(el=>el.textContent));
    assert.deepEqual(outside,[]);
    await page.screenshot({path:`tmp/profile-preview/stats-${theme}.png`});
    await page.setViewportSize({width:1000,height:294});
  }
  // Reuse the existing local README preview generated by the profile check.
  await page.setViewportSize({width:1100,height:900});
  await page.goto(pathToFileURL(path.resolve('tmp/profile-preview/index.html')).href);
  await page.screenshot({path:'tmp/profile-preview/stage2-desktop.png',fullPage:true});
  const images=await page.locator('img').evaluateAll(imgs=>imgs.map(i=>({src:i.currentSrc,loaded:i.complete&&i.naturalWidth>0})));
  assert.ok(images.every(i=>i.loaded));
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:'tmp/profile-preview/stage2-mobile.png',fullPage:true});
  console.log('README images and mobile overflow: passed');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
